#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the two consumers of tools/alert_vocab.py.

    python3 tools/gen_alert_vocab.py --check     # exit 1 if anything is stale
    python3 tools/gen_alert_vocab.py --write     # regenerate both

Consumers:
    tools/apps_script/AftsAlertVocab.gs   the whole matching engine, paste-ready
    docs/alerts.html                      the PATHOGENS / PRODUCTS / COUNTRIES
                                          arrays, between generated markers

Nothing else in either file is touched. The markers exist so a hand edit to
alerts.html elsewhere on the page survives regeneration.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from tools import alert_vocab as V  # noqa: E402

GS_PATH = os.path.join(ROOT, "tools", "apps_script", "AftsAlertVocab.gs")
HTML_PATH = os.path.join(ROOT, "docs", "alerts.html")

BEGIN = "// ===== GENERATED BY tools/gen_alert_vocab.py — DO NOT EDIT BY HAND ====="
END = "// ===== END GENERATED ====="


def js(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def _js_map(name: str, mapping: dict) -> str:
    lines = ["var %s = {" % name]
    for k, v in mapping.items():
        lines.append("  %s: %s," % (js(k), js(v)))
    lines.append("};")
    return "\n".join(lines)


def _js_array(name: str, values: list) -> str:
    out, cur = [], "  "
    for v in values:
        item = js(v) + ", "
        if len(cur) + len(item) > 76:
            out.append(cur.rstrip())
            cur = "  "
        cur += item
    if cur.strip():
        out.append(cur.rstrip().rstrip(","))
    return "var %s = [\n%s\n];" % (name, "\n".join(out))


# ---------------------------------------------------------------------------
# docs/alerts.html
# ---------------------------------------------------------------------------

def html_block() -> str:
    def arr(name, values):
        out, cur = [], "  "
        for v in values:
            item = js(v) + ","
            if len(cur) + len(item) > 74:
                out.append(cur.rstrip())
                cur = "  "
            cur += item + " "
        if cur.strip():
            out.append(cur.rstrip().rstrip(","))
        return "const %s = [\n%s\n];" % (name, "\n".join(out))

    return "\n".join([
        BEGIN,
        "// Source of truth: tools/alert_vocab.py. Every word below is a key the",
        "// Apps Script matcher (AftsAlertVocab.gs) holds an explicit token list",
        "// for, so a word offered here is a word the backend understands.",
        "// Regenerate with: python3 tools/gen_alert_vocab.py --write",
        arr("PATHOGENS", list(V.PATHOGEN.keys())),
        "",
        arr("PRODUCTS", list(V.PRODUCT.keys())),
        "",
        arr("COUNTRIES", list(V.COUNTRY)),
        END,
    ])


def render_html() -> str:
    src = open(HTML_PATH, encoding="utf-8").read()
    block = html_block()

    if BEGIN in src and END in src:
        head, rest = src.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail

    # First run: replace the three hand-written arrays and their lead comments.
    pat = re.compile(
        r"// Pathogens: aligned with.*?^\];\s*\n",
        re.S | re.M,
    )
    start = src.find("// ===== Reference pools =====")
    if start < 0:
        raise SystemExit("alerts.html: '// ===== Reference pools =====' not found")
    end_marker = "// Seed brand suggestions from the dashboard's dataset when available."
    end = src.find(end_marker)
    if end < 0:
        raise SystemExit("alerts.html: brand-seed comment not found")
    return (src[:start]
            + "// ===== Reference pools =====\n"
            + block + "\n\n"
            + src[end:])


# ---------------------------------------------------------------------------
# tools/apps_script/AftsAlertVocab.gs
# ---------------------------------------------------------------------------

GS_HEADER = r'''/**
 * AFTS FSIS — alert vocabulary and matching engine
 * =============================================================================
 * GENERATED FILE. Source of truth: tools/alert_vocab.py in
 * github.com/gstoforos/Food-Safety-Intelligence-System
 * Regenerate with:  python3 tools/gen_alert_vocab.py --write
 *
 * HOW TO INSTALL
 * --------------
 *   1. In the Apps Script project, add a new file named AftsAlertVocab.gs and
 *      paste this whole file into it.
 *   2. In the OLD alerts file, DELETE the existing recallMatchesCriterion_ and
 *      sendAlertMatchEmail_ functions. Two definitions of the same name in one
 *      project is a silent coin-flip over which one runs — this is the only
 *      step that can go wrong, so do it before the first scan.
 *   3. Run test_fsisAlertVocab() once from the editor. It sends nothing and
 *      writes nothing; it logs a pass/fail line per case.
 *
 * WHAT THIS FIXES (13 Sep 2026 alert)
 * -----------------------------------
 * The old matcher truncated the SUBSCRIBER'S RULE to its first token:
 *
 *     const base = v.split(/[\s\/()]/)[0];      // "clostridium botulinum" -> "clostridium"
 *     return !!base && p.indexOf(base) >= 0;    // matches "Clostridium perfringens"
 *
 * A subscriber watching for botulism was emailed about Clostridium
 * perfringens. The same truncation turned every species rule into a genus
 * rule: "Salmonella Enteritidis" matched "Salmonella spp.", "Listeria
 * monocytogenes" matched "Listeria innocua".
 *
 * Nothing is split at runtime any more. Every word alerts.html offers has an
 * explicit token list below, and a rule matches only through its own tokens.
 *
 * THE RULE
 * --------
 * A token matches on word boundaries, tolerating a trailing plural "s":
 *
 *     \b<token>s?\b
 *
 * (the leading \b only when the token starts with a word character, the
 * trailing s?\b only when it ends with one, so "lead (" and "(don)" still
 * work). The boundary is load-bearing: without it an "E. coli" rule matches
 * "Coliform / total bacterial count" through the substring "coli".
 *
 * Haystacks:
 *     pathogen -> Pathogen
 *     product  -> Product + " " + Reason        (product text is free-form and
 *                                                multilingual; Reason often
 *                                                names the food when Product
 *                                                is only a lot reference)
 *     country  -> Country
 *     brand    -> Brand + " " + Company         free text, no vocabulary
 */

'''

GS_ENGINE = r'''

// ---------------------------------------------------------------------------
// Matching engine
// ---------------------------------------------------------------------------

/** Regex source for one vocabulary token. Mirrors alert_vocab.token_pattern. */
function _fsisTokenRe_(token) {
  var pat = String(token).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (/^\w/.test(token)) { pat = '\\b' + pat; }
  if (/\w$/.test(token)) { pat = pat + 's?\\b'; }
  return new RegExp(pat, 'i');
}

/**
 * Token list for a subscriber rule. A term that is not in the vocabulary —
 * a brand, or a legacy rule typed by hand — falls back to the term as
 * written. It is never split.
 */
function _fsisTokensFor_(cat, term) {
  var low = String(term || '').toLowerCase().trim();
  if (!low) { return []; }
  var k;
  if (cat === 'pathogen') {
    for (k in PATHOGEN_VOCAB) {
      if (k.toLowerCase() === low) { return PATHOGEN_VOCAB[k]; }
    }
    if (PATHOGEN_LEGACY[low] && PATHOGEN_VOCAB[PATHOGEN_LEGACY[low]]) {
      return PATHOGEN_VOCAB[PATHOGEN_LEGACY[low]];
    }
    return [low];
  }
  if (cat === 'product') {
    for (k in PRODUCT_VOCAB) {
      if (k.toLowerCase() === low) { return PRODUCT_VOCAB[k]; }
    }
    return [low];
  }
  if (cat === 'country') {
    for (k in COUNTRY_ALIASES) {
      if (k.toLowerCase() === low) { return COUNTRY_ALIASES[k]; }
    }
    return [low];
  }
  return [low];
}

function _fsisHaystack_(recall, cat) {
  if (cat === 'pathogen') { return String(recall.Pathogen || ''); }
  if (cat === 'product') {
    return String(recall.Product || '') + ' ' + String(recall.Reason || '');
  }
  if (cat === 'country') { return String(recall.Country || ''); }
  if (cat === 'brand') {
    return String(recall.Brand || '') + ' ' + String(recall.Company || '');
  }
  return '';
}

/**
 * Does this register row satisfy the subscriber rule (cat, val)?
 * Drop-in replacement for the old function of the same name and signature.
 */
function recallMatchesCriterion_(recall, cat, val) {
  var toks = _fsisTokensFor_(cat, val);
  if (!toks.length) { return false; }
  var hay = _fsisHaystack_(recall, cat);
  if (!hay.replace(/\s+/g, '')) { return false; }
  for (var i = 0; i < toks.length; i++) {
    if (_fsisTokenRe_(toks[i]).test(hay)) { return true; }
  }
  return false;
}

/** Every word the subscriber form may offer, for validating a POSTed rule. */
function fsisOfferedTerms_(cat) {
  if (cat === 'pathogen') { return Object.keys(PATHOGEN_VOCAB); }
  if (cat === 'product') { return Object.keys(PRODUCT_VOCAB); }
  if (cat === 'country') { return COUNTRY_LIST.slice(); }
  return [];   // brand is free text
}

/**
 * True when a stored rule can still fire. Use it before saving a new
 * subscription, and in the weekly digest to flag rules that were retired.
 * Brand rules are always accepted; they are free text by design.
 */
function fsisRuleIsUnderstood_(cat, val) {
  if (cat === 'brand') { return true; }
  var low = String(val || '').toLowerCase().trim();
  if (!low) { return false; }
  var offered = fsisOfferedTerms_(cat);
  for (var i = 0; i < offered.length; i++) {
    if (offered[i].toLowerCase() === low) { return true; }
  }
  if (cat === 'pathogen' && PATHOGEN_LEGACY[low]) { return true; }
  return false;
}

/** Why a retired word was retired, for the "your rule no longer fires" mail. */
function fsisRetiredReason_(cat, val) {
  var low = String(val || '').toLowerCase().trim();
  var src = (cat === 'product') ? RETIRED_PRODUCT : RETIRED_PATHOGEN;
  for (var k in src) {
    if (k.toLowerCase() === low) { return src[k]; }
  }
  return '';
}
'''

GS_MAILER = r'''

// ---------------------------------------------------------------------------
// The alert email
// ---------------------------------------------------------------------------
//
// WHY THE 13 SEP EMAIL LOOKED DUPLICATED. The two rows were RappelConso fiches
// 23501 and 23502: the same lot (VA238F001) of foie gras from the same
// producer, published the same day — one sold at the factory shop, one through
// METRO. They are two notices of ONE incident, and the register says so: both
// rows carry [incident:fr:truffe-perigourdine-2026-09-11] in Notes, which is
// one of the 14 public columns in recalls.json. The weekly report already
// counts them once. This email did not know to look.
//
// Both rows are still listed — each names a different product and a different
// use-by date, and a subscriber pulling stock needs both. What changes is that
// the email no longer presents them as two unrelated findings.
//
// Grouping uses the operator-assigned [incident:<id>] tag only. It is never
// inferred here, exactly as in pipeline/_incident_id.py.

function sendAlertMatchEmail_(rule, matches, overflow, scanStart) {
  var incidentOf = function (r) {
    var m = /\[incident:([^\]]+)\]/i.exec(String(r.Notes || ''));
    return m ? m[1].trim().toLowerCase() : null;
  };

  var counts = {};
  matches.forEach(function (r) {
    var id = incidentOf(r);
    if (id) { counts[id] = (counts[id] || 0) + 1; }
  });
  var incidentCount = matches.reduce(function (n, r) {
    var id = incidentOf(r);
    return n + (id && counts[id] > 1 ? 1 / counts[id] : 1);
  }, 0);
  var incidents = Math.round(incidentCount);

  var rows = matches.map(function (r) {
    var age = _ageDays_(r.Date, scanStart);
    var ageTag = (age !== null && age > 7)
      ? ' <span style="color:#b45309;font-size:10px">(' + age + 'd ago)</span>' : '';
    var id = incidentOf(r);
    var incTag = (id && counts[id] > 1)
      ? ' <span style="color:#64748b;font-size:10px;white-space:nowrap">' +
        '· same incident (' + counts[id] + ' notices)</span>' : '';
    return '<tr>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-family:monospace;' +
        'font-size:11px;color:#64748b;white-space:nowrap">' + _esc(r.Date) + ageTag + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb">' +
        _esc(r.Company || r.Brand || '—') + incTag + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-size:12px">' +
        _esc(_trim(r.Product, 70)) + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-family:monospace;' +
        'font-size:11px;color:#ef4444"><em>' + _esc(r.Pathogen || '') + '</em></td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-size:12px;' +
        'white-space:nowrap">' + _esc(r.Country || '') + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;white-space:nowrap">' +
        (r.URL ? '<a href="' + _esc(r.URL) + '">view</a>' : '—') + '</td>' +
      '</tr>';
  }).join('');

  var n = matches.length;
  var th = 'padding:8px 10px;text-align:left;white-space:nowrap';

  var subject = (incidents < n)
    ? 'AFTS Alert: ' + incidents + ' new matching incident' + (incidents > 1 ? 's' : '') +
      ' (' + n + ' notices)'
    : 'AFTS Alert: ' + n + ' new matching recall' + (n > 1 ? 's' : '');

  var lead = (incidents < n)
    ? 'Your alert rule matched <strong>' + incidents + '</strong> new incident' +
      (incidents > 1 ? 's' : '') + ', published as <strong>' + n + '</strong> separate ' +
      'regulator notices. Notices from the same incident are marked below — each ' +
      'names a different product or pack, so check all of them.'
    : 'Your alert rule matched <strong>' + n + '</strong> new recall' + (n > 1 ? 's' : '') + ':';

  MailApp.sendEmail({
    to: rule.email, name: FROM_NAME,
    subject: subject,
    htmlBody:
      '<p>Hi ' + _esc(rule.name) + ',</p>' +
      '<p>' + lead + '</p>' +
      '<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;' +
        'font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif">' +
      '<thead><tr style="background:#0a0e1a;color:#fbbf24;font-family:monospace;' +
        'font-size:10px;letter-spacing:.08em">' +
      '<th style="' + th + '">PUBLISHED</th><th style="' + th + '">FIRM</th>' +
      '<th style="' + th + '">PRODUCT</th><th style="' + th + '">PATHOGEN</th>' +
      '<th style="' + th + '">COUNTRY</th><th style="' + th + '">LINK</th></tr></thead>' +
      '<tbody>' + rows + '</tbody></table>' +
      (overflow
        ? '<p style="font-size:12px;color:#b45309;margin-top:14px">' +
          '+' + overflow + ' further match' + (overflow > 1 ? 'es' : '') +
          ' held back from this email. They will follow in the next scan.</p>'
        : '') +
      '<p style="font-size:12px;color:#64748b;margin-top:14px">PUBLISHED is the date the ' +
      'regulator issued the notice. Always check the source page for the current return ' +
      'or destruction deadline before acting.</p>' +
      _manageFooter_(rule.tok)
  });
}
'''

GS_TESTS = r'''

// ---------------------------------------------------------------------------
// Self-test. Sends nothing, writes nothing. Run it from the editor.
// ---------------------------------------------------------------------------

function test_fsisAlertVocab() {
  var bad = 0;
  var check = function (label, got, want) {
    if (got !== want) { bad++; }
    Logger.log((got === want ? 'ok   ' : 'FAIL ') + label + ' -> ' + got);
  };

  // --- the 13 Sep defect and its neighbours ------------------------------
  var cases = [
    ['pathogen', 'Clostridium botulinum',   {Pathogen: 'Clostridium perfringens'},          false, 'THE BUG'],
    ['pathogen', 'Clostridium botulinum',   {Pathogen: 'C. botulinum'},                     true,  'abbreviated genus'],
    ['pathogen', 'Clostridium botulinum',   {Pathogen: 'Clostridium botulinum'},            true,  'exact'],
    ['pathogen', 'Clostridium perfringens', {Pathogen: 'Clostridium perfringens'},          true,  '13 Sep row still matches its own rule'],
    ['pathogen', 'Listeria',                {Pathogen: 'Listeria monocytogenes'},           true,  'genus rule, species row'],
    ['pathogen', 'Salmonella',              {Pathogen: 'Salmonella Enteritidis'},           true,  'genus rule, serovar row'],
    ['pathogen', 'E. coli / STEC',          {Pathogen: 'Shiga toxin-producing E. coli (STEC)'}, true, 'STEC'],
    ['pathogen', 'E. coli / STEC',          {Pathogen: 'Coliform / total bacterial count'}, false, 'the word-boundary trap'],
    ['pathogen', 'Bacillus cereus / cereulide', {Pathogen: 'Cereulide (B. cereus toxin)'},  true,  'toxin spelling'],
    ['pathogen', 'Ochratoxin',              {Pathogen: 'Ochratoxin A'},                     true,  'A-suffix'],
    ['pathogen', 'Ochratoxin A',            {Pathogen: 'Ochratoxin'},                       true,  'legacy rule still fires'],
    ['pathogen', 'Aflatoxin',               {Pathogen: 'Aflatoxin B1 + Ochratoxin A'},      true,  'compound row'],
    ['pathogen', 'Mold / spoilage',         {Pathogen: 'Mold'},                             true,  'US spelling is canonical'],
    ['pathogen', 'Foreign material / physical hazard', {Pathogen: 'Foreign material (glass)'}, true, 'free-text family'],
    ['pathogen', 'Heavy metals',            {Pathogen: 'Cadmium (heavy metal)'},            true,  'free-text family'],
    ['pathogen', 'T-2 / HT-2 toxin',        {Pathogen: 'Mycotoxins (T-2 and HT-2 toxin)'},  true,  'T-2 inside a phrase'],
    ['pathogen', 'Listeria',                {Pathogen: ''},                                 false, 'empty field never matches'],

    ['country',  'Czechia',                 {Country: 'Czechia'},                           true,  'register spelling'],
    ['country',  'Czechia',                 {Country: 'Czech Republic'},                    true,  'alias'],
    ['country',  'Korea, South',            {Country: 'Korea, South'},                      true,  'register spelling'],
    ['country',  'Turkey',                  {Country: 'Turkey'},                            true,  'register spelling'],
    ['country',  'EU-wide / multi-country', {Country: 'Multiple EU/EEA + UK'},              true,  'multi-country bucket'],
    ['country',  'France',                  {Country: 'Belgium / France'},                  true,  'compound origin'],

    ['product',  'Dairy — cheese',          {Product: 'Tomme de Burdignes', Reason: ''},    true,  'regional cheese name'],
    ['product',  'Dairy — cheese',          {Product: 'lardons fumés pxm 200g', Reason: ''}, false, 'not cheese'],
    ['product',  'Meat — pork',             {Product: 'lardons fumés pxm 200g', Reason: ''}, true,  'fr pork'],
    ['product',  'Dried fruit / nuts',      {Product: 'Ochratoxin A in organic dried figs from Turkey', Reason: ''}, true, 'plural token'],
    ['product',  'Dried fruit / nuts',      {Product: 'best before date 12/2026', Reason: ''}, false, '"date" is not a dried date'],

    ['brand',    'Ferrarini',               {Brand: 'Ferrarini', Company: ''},              true,  'free-text brand'],
    ['brand',    'Ferrarini',               {Brand: '', Company: 'Ferrarini S.p.A.'},       true,  'brand found in company'],
    ['brand',    'Ferrarini',               {Brand: 'Ferrari', Company: ''},                false, 'not a prefix match']
  ];
  cases.forEach(function (c) {
    check('[' + c[0] + '] "' + c[1] + '" vs ' + JSON.stringify(c[2]) + '  (' + c[4] + ')',
          recallMatchesCriterion_(c[2], c[0], c[1]), c[3]);
  });

  // --- vocabulary integrity ---------------------------------------------
  var k, i;
  for (k in PATHOGEN_VOCAB) {
    if (!PATHOGEN_VOCAB[k].length) { bad++; Logger.log('FAIL empty token list: ' + k); }
  }
  for (k in PRODUCT_VOCAB) {
    if (!PRODUCT_VOCAB[k].length) { bad++; Logger.log('FAIL empty token list: ' + k); }
  }
  for (k in PATHOGEN_LEGACY) {
    if (!PATHOGEN_VOCAB[PATHOGEN_LEGACY[k]]) {
      bad++; Logger.log('FAIL legacy "' + k + '" points at a term that no longer exists');
    }
  }
  for (k in COUNTRY_ALIASES) {
    if (COUNTRY_LIST.indexOf(k) < 0) {
      bad++; Logger.log('FAIL alias key not in COUNTRY_LIST: ' + k);
    }
  }
  // Every retired word must be REJECTED by the form and, if it is a pathogen
  // with a legacy mapping, must still fire for existing subscribers.
  for (k in RETIRED_PATHOGEN) {
    if (fsisRuleIsUnderstood_('pathogen', k) && !PATHOGEN_LEGACY[k.toLowerCase()]) {
      bad++; Logger.log('FAIL retired word still offered: ' + k);
    }
  }

  check('Yersinia is offered (recognised, no rows yet)',
        fsisRuleIsUnderstood_('pathogen', 'Yersinia'), true);
  check('"Undeclared allergen" is no longer offered',
        fsisRuleIsUnderstood_('pathogen', 'Undeclared allergen'), false);
  check('"Rotavirus" is no longer offered',
        fsisRuleIsUnderstood_('pathogen', 'Rotavirus'), false);

  Logger.log(bad ? ('FAILURES: ' + bad) : 'All alert-vocabulary cases pass.');
  return bad === 0;
}
'''


def render_gs() -> str:
    parts = [GS_HEADER, BEGIN, ""]
    parts.append("var FSIS_VOCAB_VERSION = %s;" % js(VERSION))
    parts.append("")
    parts.append(_js_map("PATHOGEN_VOCAB", V.PATHOGEN))
    parts.append("")
    parts.append(_js_map("PRODUCT_VOCAB", V.PRODUCT))
    parts.append("")
    parts.append(_js_array("COUNTRY_LIST", V.COUNTRY))
    parts.append("")
    parts.append(_js_map("COUNTRY_ALIASES", V.COUNTRY_ALIASES))
    parts.append("")
    parts.append(_js_map("PATHOGEN_LEGACY", V.PATHOGEN_LEGACY))
    parts.append("")
    parts.append(_js_map("RETIRED_PATHOGEN", V.RETIRED_PATHOGEN))
    parts.append("")
    parts.append(_js_map("RETIRED_PRODUCT", V.RETIRED_PRODUCT))
    parts.append("")
    parts.append(END)
    parts.append(GS_ENGINE)
    parts.append(GS_MAILER)
    parts.append(GS_TESTS)
    return "\n".join(parts).rstrip() + "\n"


VERSION = "2026-09-14"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("pass --write or --check")

    targets = [(GS_PATH, render_gs()), (HTML_PATH, render_html())]
    stale = []
    for path, want in targets:
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == want:
            continue
        stale.append(path)
        if args.write:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(want)

    rel = [os.path.relpath(p, ROOT) for p in stale]
    if args.write:
        print("wrote: " + (", ".join(rel) if rel else "(nothing — already current)"))
        return 0
    if stale:
        print("STALE: " + ", ".join(rel))
        print("run: python3 tools/gen_alert_vocab.py --write")
        return 1
    print("alert vocabulary is in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
