#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the two consumers of tools/alert_vocab.py.

    python3 tools/gen_alert_vocab.py --check     # exit 1 if anything is stale
    python3 tools/gen_alert_vocab.py --write     # regenerate both

Consumers:
    tools/apps_script/AftsAlerts.gs   the COMPLETE deployed Apps Script file,
                                      paste-ready: AftsAlerts.base.gs with the
                                      vocabulary, the matching engine and the
                                      incident-grouped mailer merged in
    docs/alerts.html                  the PATHOGENS / PRODUCTS / COUNTRIES
                                      arrays, between generated markers

AftsAlerts.base.gs is the deployed file as the operator sent it on 2026-09-14.
It is the template, never edited by this script, so `git diff` on it shows any
drift between the Apps Script project and what we generate against.

Nothing else in either file is touched. The markers exist so a hand edit to
alerts.html elsewhere on the page survives regeneration.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from tools import alert_vocab as V  # noqa: E402

BASE_PATH = os.path.join(ROOT, "tools", "apps_script", "AftsAlerts.base.gs")
GS_PATH = os.path.join(ROOT, "tools", "apps_script", "AftsAlerts.gs")
HTML_PATH = os.path.join(ROOT, "docs", "alerts.html")

VERSION = "2026-09-14"

BEGIN = "// ===== GENERATED BY tools/gen_alert_vocab.py — DO NOT EDIT BY HAND ====="
END = "// ===== END GENERATED ====="


def js(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def _js_map(name: str, mapping: dict) -> str:
    lines = ["var %s = {" % name]
    for k, v in mapping.items():
        lines.append("  %s: %s," % (js(k), js(v)))
    lines.append("};")
    return "\n".join(lines)


def _js_array(name: str, values: list) -> str:
    out, cur = [], "  "
    for v in values:
        item = js(v) + ", "
        if len(cur) + len(item) > 76:
            out.append(cur.rstrip())
            cur = "  "
        cur += item
    if cur.strip():
        out.append(cur.rstrip().rstrip(","))
    return "var %s = [\n%s\n];" % (name, "\n".join(out))


# ---------------------------------------------------------------------------
# docs/alerts.html
# ---------------------------------------------------------------------------

def html_block() -> str:
    def arr(name, values):
        out, cur = [], "  "
        for v in values:
            item = js(v) + ","
            if len(cur) + len(item) > 74:
                out.append(cur.rstrip())
                cur = "  "
            cur += item + " "
        if cur.strip():
            out.append(cur.rstrip().rstrip(","))
        return "const %s = [\n%s\n];" % (name, "\n".join(out))

    return "\n".join([
        BEGIN,
        "// Source of truth: tools/alert_vocab.py. Every word below is a key the",
        "// Apps Script matcher (AftsAlertVocab.gs) holds an explicit token list",
        "// for, so a word offered here is a word the backend understands.",
        "// Regenerate with: python3 tools/gen_alert_vocab.py --write",
        arr("PATHOGENS", list(V.PATHOGEN.keys())),
        "",
        arr("PRODUCTS", list(V.PRODUCT.keys())),
        "",
        arr("COUNTRIES", list(V.COUNTRY)),
        END,
    ])


def render_html() -> str:
    src = open(HTML_PATH, encoding="utf-8").read()
    block = html_block()

    if BEGIN in src and END in src:
        head, rest = src.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        return head + block + tail

    # First run: replace the three hand-written arrays and their lead comments.
    pat = re.compile(
        r"// Pathogens: aligned with.*?^\];\s*\n",
        re.S | re.M,
    )
    start = src.find("// ===== Reference pools =====")
    if start < 0:
        raise SystemExit("alerts.html: '// ===== Reference pools =====' not found")
    end_marker = "// Seed brand suggestions from the dashboard's dataset when available."
    end = src.find(end_marker)
    if end < 0:
        raise SystemExit("alerts.html: brand-seed comment not found")
    return (src[:start]
            + "// ===== Reference pools =====\n"
            + block + "\n\n"
            + src[end:])


# ---------------------------------------------------------------------------
# The blocks spliced into the base file
# ---------------------------------------------------------------------------

VOCAB_GATE = r'''
  // VOCABULARY GATE (2026-09-14).
  //
  // alerts.html offers a fixed word list generated from the same definition
  // as PATHOGEN_VOCAB / PRODUCT_VOCAB / COUNTRY_LIST below, so a term the
  // form can produce is always a term the matcher understands. A term it
  // CANNOT understand would be stored as an active rule that can never fire:
  // the subscriber waits forever and nothing anywhere says why. That is how
  // "Undeclared allergen" and "Rotavirus" sat on the form for months.
  //
  // Brand is exempt — it is free text by design.
  const unknown = _firstUnknownTerm_([[slot1_cat, slot1_val],
                                      [slot2_cat, slot2_val]]);
  if (unknown) {
    Logger.log('REJECT ' + email + ' — ' + unknown.cat + ' "' + unknown.val +
               '" is not in the alert vocabulary. ' + (unknown.reason || ''));
    return {ok: false, error: 'unknown_term', category: unknown.cat,
            value: unknown.val, reason: unknown.reason ||
            'not offered by the alert form'};
  }
'''

GS_ENGINE = r'''
// ---------------------------------------------------------------------------
// MATCHING ENGINE  (2026-09-14 — replaces the first-token truncation)
// ---------------------------------------------------------------------------

/**
 * Regex source for one vocabulary token: word-boundaried, plural-tolerant.
 * Mirrors alert_vocab.token_pattern in the FSIS repo, and tests/
 * test_alert_vocab.py fails if the two ever disagree on a case.
 */
function _fsisTokenRe_(token) {
  var pat = String(token).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (/^\w/.test(token)) { pat = '\\b' + pat; }
  if (/\w$/.test(token)) { pat = pat + 's?\\b'; }
  return new RegExp(pat, 'i');
}

/**
 * Token list for a subscriber rule.
 *
 * A term that is not in the vocabulary — a brand, or a legacy rule typed by
 * hand before the vocabulary existed — falls back to the term AS WRITTEN.
 * It is never split. That fallback is the whole difference from the old
 * behaviour: an unrecognised rule now matches too little, not too much.
 */
function _fsisTokensFor_(cat, term) {
  var low = String(term || '').toLowerCase().trim();
  if (!low) { return []; }
  var k;
  if (cat === 'pathogen') {
    for (k in PATHOGEN_VOCAB) {
      if (k.toLowerCase() === low) { return PATHOGEN_VOCAB[k]; }
    }
    if (PATHOGEN_LEGACY[low] && PATHOGEN_VOCAB[PATHOGEN_LEGACY[low]]) {
      return PATHOGEN_VOCAB[PATHOGEN_LEGACY[low]];
    }
    return [low];
  }
  if (cat === 'product') {
    for (k in PRODUCT_VOCAB) {
      if (k.toLowerCase() === low) { return PRODUCT_VOCAB[k]; }
    }
    return [low];
  }
  if (cat === 'country') {
    for (k in COUNTRY_ALIASES) {
      if (k.toLowerCase() === low) { return COUNTRY_ALIASES[k]; }
    }
    return [low];
  }
  return [low];
}

/**
 * The text a category is matched against.
 *
 * `product` deliberately includes Reason. Product is free-form and
 * multilingual (fr/pl/it/es/de all occur) and is frequently nothing but a lot
 * reference — "lot 362627", "rillebio-130gr" — while Reason usually names the
 * food. Searching Product alone loses those rows entirely.
 */
function _fsisHaystack_(recall, cat) {
  if (cat === 'pathogen') { return String(recall.Pathogen || ''); }
  if (cat === 'product') {
    return String(recall.Product || '') + ' ' + String(recall.Reason || '');
  }
  if (cat === 'country') { return String(recall.Country || ''); }
  if (cat === 'brand') {
    return String(recall.Brand || '') + ' ' + String(recall.Company || '');
  }
  return '';
}

/**
 * Does this register row satisfy the subscriber rule (cat, val)?
 * Same name and signature as the function it replaces.
 */
function recallMatchesCriterion_(recall, cat, val) {
  var toks = _fsisTokensFor_(cat, val);
  if (!toks.length) { return false; }
  var hay = _fsisHaystack_(recall, cat);
  if (!hay.replace(/\s+/g, '')) { return false; }
  for (var i = 0; i < toks.length; i++) {
    if (_fsisTokenRe_(toks[i]).test(hay)) { return true; }
  }
  return false;
}

/** Every word the subscribe form may offer for a category. */
function fsisOfferedTerms_(cat) {
  if (cat === 'pathogen') { return Object.keys(PATHOGEN_VOCAB); }
  if (cat === 'product') { return Object.keys(PRODUCT_VOCAB); }
  if (cat === 'country') { return COUNTRY_LIST.slice(); }
  return [];   // brand is free text
}

/**
 * True when a stored rule can still fire. Brand rules are always accepted;
 * they are free text by design.
 */
function fsisRuleIsUnderstood_(cat, val) {
  if (cat === 'brand') { return true; }
  var low = String(val || '').toLowerCase().trim();
  if (!low) { return false; }
  var offered = fsisOfferedTerms_(cat);
  for (var i = 0; i < offered.length; i++) {
    if (offered[i].toLowerCase() === low) { return true; }
  }
  if (cat === 'pathogen' && PATHOGEN_LEGACY[low]) { return true; }
  return false;
}

/** Why a retired word was retired, for the rejection message and the audit. */
function fsisRetiredReason_(cat, val) {
  var low = String(val || '').toLowerCase().trim();
  var src = (cat === 'product') ? RETIRED_PRODUCT : RETIRED_PATHOGEN;
  for (var k in src) {
    if (k.toLowerCase() === low) { return src[k]; }
  }
  return '';
}

/**
 * First (category, value) pair in the list that the matcher cannot understand,
 * or null. Empty slots and brand slots are skipped.
 */
function _firstUnknownTerm_(pairs) {
  for (var i = 0; i < pairs.length; i++) {
    var cat = String(pairs[i][0] || '').trim();
    var val = String(pairs[i][1] || '').trim();
    if (!cat || !val || cat === 'brand') { continue; }
    if (!fsisRuleIsUnderstood_(cat, val)) {
      return {cat: cat, val: val, reason: fsisRetiredReason_(cat, val)};
    }
  }
  return null;
}
'''

GS_ADMIN = r'''

/**
 * Report every ACTIVE rule whose stored term the matcher no longer
 * understands — a rule that will never fire again, silently.
 *
 * Sends nothing and writes nothing. Run it once after deploying: anything it
 * lists is a subscriber who needs an email asking them to pick a new word.
 * Legacy spellings that PATHOGEN_LEGACY maps forward ("Ochratoxin A" and
 * friends) are NOT listed — those still match.
 */
function auditStoredRules() {
  const {sh, H} = _alertsHeaderMap_();
  const data = sh.getDataRange().getValues();
  let active = 0, dead = 0;
  for (let i = 1; i < data.length; i++) {
    if (String(data[i][H.status]).toLowerCase() !== 'active') continue;
    active++;
    [['slot1', data[i][H.slot1_cat], data[i][H.slot1_val]],
     ['slot2', data[i][H.slot2_cat], data[i][H.slot2_val]]
    ].forEach(([slot, cat, val]) => {
      cat = String(cat || '').trim();
      val = String(val || '').trim();
      if (!cat || !val || cat === 'brand') return;
      if (fsisRuleIsUnderstood_(cat, val)) return;
      dead++;
      const why = fsisRetiredReason_(cat, val) || 'not in the alert vocabulary';
      Logger.log('DEAD  row ' + (i + 1) + '  ' + data[i][H.email] +
                 '  ' + slot + ' ' + cat + '="' + val + '"  — ' + why);
    });
  }
  Logger.log('Audit: ' + active + ' active rule(s), ' + dead +
             ' criterion(s) that can never match.');
  return dead;
}
'''


GS_TESTS = r'''
/**
 * Alert-vocabulary self-test. Sends nothing, writes nothing, touches no sheet
 * and makes no network call. Run it from the editor after every regeneration.
 */
function test_fsisAlertVocab() {
  var bad = 0;
  var check = function (label, got, want) {
    if (got !== want) { bad++; }
    Logger.log((got === want ? 'ok   ' : 'FAIL ') + label + ' -> ' + got);
  };

  // --- the 13 Sep defect and its neighbours ------------------------------
  var cases = [
    ['pathogen', 'Clostridium botulinum',   {Pathogen: 'Clostridium perfringens'},          false, 'THE BUG'],
    ['pathogen', 'Clostridium botulinum',   {Pathogen: 'C. botulinum'},                     true,  'abbreviated genus'],
    ['pathogen', 'Clostridium botulinum',   {Pathogen: 'Clostridium botulinum'},            true,  'exact'],
    ['pathogen', 'Clostridium perfringens', {Pathogen: 'Clostridium perfringens'},          true,  '13 Sep row still matches its own rule'],
    ['pathogen', 'Listeria',                {Pathogen: 'Listeria monocytogenes'},           true,  'genus rule, species row'],
    ['pathogen', 'Salmonella',              {Pathogen: 'Salmonella Enteritidis'},           true,  'genus rule, serovar row'],
    ['pathogen', 'E. coli / STEC',          {Pathogen: 'Shiga toxin-producing E. coli (STEC)'}, true, 'STEC'],
    ['pathogen', 'E. coli / STEC',          {Pathogen: 'Coliform / total bacterial count'}, false, 'the word-boundary trap'],
    ['pathogen', 'Bacillus cereus / cereulide', {Pathogen: 'Cereulide (B. cereus toxin)'},  true,  'toxin spelling'],
    ['pathogen', 'Ochratoxin',              {Pathogen: 'Ochratoxin A'},                     true,  'A-suffix'],
    ['pathogen', 'Ochratoxin A',            {Pathogen: 'Ochratoxin'},                       true,  'legacy rule still fires'],
    ['pathogen', 'Aflatoxin',               {Pathogen: 'Aflatoxin B1 + Ochratoxin A'},      true,  'compound row'],
    ['pathogen', 'Mold / spoilage',         {Pathogen: 'Mold'},                             true,  'US spelling is canonical'],
    ['pathogen', 'Foreign material / physical hazard', {Pathogen: 'Foreign material (glass)'}, true, 'free-text family'],
    ['pathogen', 'Heavy metals',            {Pathogen: 'Cadmium (heavy metal)'},            true,  'free-text family'],
    ['pathogen', 'T-2 / HT-2 toxin',        {Pathogen: 'Mycotoxins (T-2 and HT-2 toxin)'},  true,  'T-2 inside a phrase'],
    ['pathogen', 'Listeria',                {Pathogen: ''},                                 false, 'empty field never matches'],

    ['country',  'Czechia',                 {Country: 'Czechia'},                           true,  'register spelling'],
    ['country',  'Czechia',                 {Country: 'Czech Republic'},                    true,  'alias'],
    ['country',  'Korea, South',            {Country: 'Korea, South'},                      true,  'register spelling'],
    ['country',  'Turkey',                  {Country: 'Turkey'},                            true,  'register spelling'],
    ['country',  'EU-wide / multi-country', {Country: 'Multiple EU/EEA + UK'},              true,  'multi-country bucket'],
    ['country',  'France',                  {Country: 'Belgium / France'},                  true,  'compound origin'],

    ['product',  'Dairy — cheese',          {Product: 'Tomme de Burdignes', Reason: ''},    true,  'regional cheese name'],
    ['product',  'Dairy — cheese',          {Product: 'lardons fumés pxm 200g', Reason: ''}, false, 'not cheese'],
    ['product',  'Meat — pork',             {Product: 'lardons fumés pxm 200g', Reason: ''}, true,  'fr pork'],
    ['product',  'Dried fruit / nuts',      {Product: 'Ochratoxin A in organic dried figs from Turkey', Reason: ''}, true, 'plural token'],
    ['product',  'Dried fruit / nuts',      {Product: 'best before date 12/2026', Reason: ''}, false, '"date" is not a dried date'],

    ['brand',    'Ferrarini',               {Brand: 'Ferrarini', Company: ''},              true,  'free-text brand'],
    ['brand',    'Ferrarini',               {Brand: '', Company: 'Ferrarini S.p.A.'},       true,  'brand found in company'],
    ['brand',    'Ferrarini',               {Brand: 'Ferrari', Company: ''},                false, 'not a prefix match']
  ];
  cases.forEach(function (c) {
    check('[' + c[0] + '] "' + c[1] + '" vs ' + JSON.stringify(c[2]) + '  (' + c[4] + ')',
          recallMatchesCriterion_(c[2], c[0], c[1]), c[3]);
  });

  // --- vocabulary integrity ---------------------------------------------
  var k, i;
  for (k in PATHOGEN_VOCAB) {
    if (!PATHOGEN_VOCAB[k].length) { bad++; Logger.log('FAIL empty token list: ' + k); }
  }
  for (k in PRODUCT_VOCAB) {
    if (!PRODUCT_VOCAB[k].length) { bad++; Logger.log('FAIL empty token list: ' + k); }
  }
  for (k in PATHOGEN_LEGACY) {
    if (!PATHOGEN_VOCAB[PATHOGEN_LEGACY[k]]) {
      bad++; Logger.log('FAIL legacy "' + k + '" points at a term that no longer exists');
    }
  }
  for (k in COUNTRY_ALIASES) {
    if (COUNTRY_LIST.indexOf(k) < 0) {
      bad++; Logger.log('FAIL alias key not in COUNTRY_LIST: ' + k);
    }
  }
  // Every retired word must be REJECTED by the form and, if it is a pathogen
  // with a legacy mapping, must still fire for existing subscribers.
  for (k in RETIRED_PATHOGEN) {
    if (fsisRuleIsUnderstood_('pathogen', k) && !PATHOGEN_LEGACY[k.toLowerCase()]) {
      bad++; Logger.log('FAIL retired word still offered: ' + k);
    }
  }

  check('Yersinia is offered (recognised, no rows yet)',
        fsisRuleIsUnderstood_('pathogen', 'Yersinia'), true);
  check('"Undeclared allergen" is no longer offered',
        fsisRuleIsUnderstood_('pathogen', 'Undeclared allergen'), false);
  check('"Rotavirus" is no longer offered',
        fsisRuleIsUnderstood_('pathogen', 'Rotavirus'), false);

  Logger.log(bad ? ('FAILURES: ' + bad) : 'All alert-vocabulary cases pass.');
  return bad === 0;
}
'''


GS_MAILER = r'''
/**
 * The match email.
 *
 * WHY THE 13 SEP EMAIL LOOKED DUPLICATED. The two rows were RappelConso fiches
 * 23501 and 23502: the same lot (VA238F001) of foie gras from the same
 * producer, published the same day — one sold at the factory shop, one through
 * METRO. They are two notices of ONE incident, and the register says so: both
 * rows carry [incident:fr:truffe-perigourdine-2026-09-11] in Notes, which is
 * one of the 14 public columns in recalls.json. The weekly report already
 * counts them once. This email did not know to look.
 *
 * Both rows are still listed — each names a different product and a different
 * use-by date, and a subscriber pulling stock needs both. What changes is that
 * the email no longer presents them as two unrelated findings.
 *
 * Grouping uses the operator-assigned [incident:<id>] tag only. It is never
 * inferred here, exactly as in pipeline/_incident_id.py.
 */
function sendAlertMatchEmail_(rule, matches, overflow, scanStart) {
  var incidentOf = function (r) {
    var m = /\[incident:([^\]]+)\]/i.exec(String(r.Notes || ''));
    return m ? m[1].trim().toLowerCase() : null;
  };

  var counts = {};
  matches.forEach(function (r) {
    var id = incidentOf(r);
    if (id) { counts[id] = (counts[id] || 0) + 1; }
  });
  var incidentCount = matches.reduce(function (n, r) {
    var id = incidentOf(r);
    return n + (id && counts[id] > 1 ? 1 / counts[id] : 1);
  }, 0);
  var incidents = Math.round(incidentCount);

  var rows = matches.map(function (r) {
    var age = _ageDays_(r.Date, scanStart);
    var ageTag = (age !== null && age > 7)
      ? ' <span style="color:#b45309;font-size:10px">(' + age + 'd ago)</span>' : '';
    var id = incidentOf(r);
    var incTag = (id && counts[id] > 1)
      ? ' <span style="color:#64748b;font-size:10px;white-space:nowrap">' +
        '· same incident (' + counts[id] + ' notices)</span>' : '';
    return '<tr>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-family:monospace;' +
        'font-size:11px;color:#64748b;white-space:nowrap">' + _esc(r.Date) + ageTag + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb">' +
        _esc(r.Company || r.Brand || '—') + incTag + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-size:12px">' +
        _esc(_trim(r.Product, 70)) + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-family:monospace;' +
        'font-size:11px;color:#ef4444"><em>' + _esc(r.Pathogen || '') + '</em></td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;font-size:12px;' +
        'white-space:nowrap">' + _esc(r.Country || '') + '</td>' +
      '<td style="padding:6px 10px;border-bottom:1px solid #e5e7eb;white-space:nowrap">' +
        (r.URL ? '<a href="' + _esc(r.URL) + '">view</a>' : '—') + '</td>' +
      '</tr>';
  }).join('');

  var n = matches.length;
  var th = 'padding:8px 10px;text-align:left;white-space:nowrap';

  var subject = (incidents < n)
    ? 'AFTS Alert: ' + incidents + ' new matching incident' + (incidents > 1 ? 's' : '') +
      ' (' + n + ' notices)'
    : 'AFTS Alert: ' + n + ' new matching recall' + (n > 1 ? 's' : '');

  var lead = (incidents < n)
    ? 'Your alert rule matched <strong>' + incidents + '</strong> new incident' +
      (incidents > 1 ? 's' : '') + ', published as <strong>' + n + '</strong> separate ' +
      'regulator notices. Notices from the same incident are marked below — each ' +
      'names a different product or pack, so check all of them.'
    : 'Your alert rule matched <strong>' + n + '</strong> new recall' + (n > 1 ? 's' : '') + ':';

  MailApp.sendEmail({
    to: rule.email, name: FROM_NAME,
    subject: subject,
    htmlBody:
      '<p>Hi ' + _esc(rule.name) + ',</p>' +
      '<p>' + lead + '</p>' +
      '<table cellpadding="0" cellspacing="0" style="border-collapse:collapse;width:100%;' +
        'font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif">' +
      '<thead><tr style="background:#0a0e1a;color:#fbbf24;font-family:monospace;' +
        'font-size:10px;letter-spacing:.08em">' +
      '<th style="' + th + '">PUBLISHED</th><th style="' + th + '">FIRM</th>' +
      '<th style="' + th + '">PRODUCT</th><th style="' + th + '">PATHOGEN</th>' +
      '<th style="' + th + '">COUNTRY</th><th style="' + th + '">LINK</th></tr></thead>' +
      '<tbody>' + rows + '</tbody></table>' +
      (overflow
        ? '<p style="font-size:12px;color:#b45309;margin-top:14px">' +
          '+' + overflow + ' further match' + (overflow > 1 ? 'es' : '') +
          ' held back from this email. They will follow in the next scan.</p>'
        : '') +
      '<p style="font-size:12px;color:#64748b;margin-top:14px">PUBLISHED is the date the ' +
      'regulator issued the notice. Always check the source page for the current return ' +
      'or destruction deadline before acting.</p>' +
      _manageFooter_(rule.tok)
  });
}
'''




# ---------------------------------------------------------------------------
# tools/apps_script/AftsAlerts.gs  —  the complete deployed file
# ---------------------------------------------------------------------------
#
# The base file is the operator's deployed script, verbatim. This merge makes
# exactly four changes to it and touches nothing else:
#
#   1. a revision block in the header docstring
#   2. a vocabulary gate in processAlertSubmission_, so a rule the matcher
#      cannot understand is refused at submission instead of being stored as
#      an active rule that silently never fires
#   3. recallMatchesCriterion_  replaced by the vocabulary-driven engine
#   4. sendAlertMatchEmail_     replaced by the incident-grouped version
#
# plus the generated vocabulary block and two new admin/self-test functions.

REVISION_NOTE = r''' *
 * ---------------------------------------------------------------------------
 * REVISION 2026-09-14 — SHARED VOCABULARY
 * ---------------------------------------------------------------------------
 * GENERATED FROM tools/alert_vocab.py in the FSIS repo. Do not hand-edit the
 * vocabulary block or the matching engine here; edit alert_vocab.py and run
 *
 *     python3 tools/gen_alert_vocab.py --write
 *
 * which rewrites BOTH this file and the word list docs/alerts.html offers,
 * so the two can never drift again. The base of this file —
 * tools/apps_script/AftsAlerts.base.gs — is the 2026-07-25 script verbatim.
 *
 * SYMPTOM
 *   On 13 Sep a subscriber whose rule is "Clostridium botulinum" was emailed
 *   about Clostridium PERFRINGENS, and the two rows in that email read as a
 *   duplicate.
 *
 * ROOT CAUSE 1 — the rule was truncated to its first token
 *   recallMatchesCriterion_ did this:
 *
 *       const base = v.split(/[\s\/()]/)[0];    // "clostridium botulinum"
 *       return !!base && p.indexOf(base) >= 0;  //   -> "clostridium"
 *
 *   The comment above it said the intent was "loose containment lets rule
 *   'Listeria' match 'Listeria monocytogenes'". That intent is right, but
 *   truncating the RULE does the opposite of what it says: it widens a
 *   SPECIES rule into a GENUS rule. Every one of these fired wrongly:
 *
 *       rule "Clostridium botulinum"   matched  "Clostridium perfringens"
 *       rule "Salmonella Enteritidis"  matched  "Salmonella spp."
 *       rule "Listeria monocytogenes"  matched  "Listeria innocua"
 *
 *   A subscriber watching for botulism — the one hazard in this register
 *   that kills without a dose response — was told a foie gras had it.
 *
 * ROOT CAUSE 2 — the form and this script never shared a definition
 *   alerts.html carried the comment "the backend matches on exact string
 *   equality so the Apps Script reuses this list". It did not, and never
 *   had. Five of the 28 words the form offered could not match anything the
 *   pipeline is capable of emitting:
 *
 *       Undeclared allergen   allergen-only notices are blocked by
 *                             pipeline/_publish_gate.py and never reach
 *                             recalls.json
 *       Rotavirus             no PATHOGEN_RULES entry, no row, ever
 *       Toxoplasma            ditto
 *       Trichinella           ditto
 *       Cryptosporidium       ditto
 *       Pet food (product)    no scraper ingests companion-animal recalls
 *
 *   and four more were near-misses against the register's own spelling:
 *   "Ochratoxin A" (the register writes both forms), "Czech Republic"
 *   (Czechia), "South Korea" (Korea, South), "Türkiye" (Turkey).
 *
 * THE FIX
 *   Every word the form offers is a key of PATHOGEN_VOCAB / PRODUCT_VOCAB /
 *   COUNTRY_LIST below with an EXPLICIT token list. Nothing is split at
 *   runtime. A token matches on word boundaries, tolerating a trailing
 *   plural "s":
 *
 *       \b<token>s?\b
 *
 *   (leading \b only when the token starts with a word character, trailing
 *   s?\b only when it ends with one, so "lead (" and "(don)" still work).
 *   The boundary is load-bearing: without it an "E. coli" rule reaches
 *   "Coliform / total bacterial count" through the substring "coli", and a
 *   "nut" token reaches "minute".
 *
 *   Haystacks:
 *       pathogen -> Pathogen
 *       product  -> Product + " " + Reason   (Product is free-form and
 *                                             multilingual, and is often only
 *                                             a lot reference; Reason usually
 *                                             names the food)
 *       country  -> Country
 *       brand    -> Brand + " " + Company    free text, no vocabulary
 *
 *   35 pathogen words now reach all 1,693 published rows — no row is
 *   invisible to every alert. Yersinia, Shigella and Brucella sit at zero
 *   rows deliberately: they are PATHOGEN_RULES labels, so the scrapers
 *   collect them and normalize_pathogen() can emit them. That is different
 *   from Rotavirus, which nothing anywhere can produce.
 *
 *   PATHOGEN_LEGACY maps the renamed words forward, so an existing
 *   subscriber whose stored rule says "Ochratoxin A" keeps matching. No
 *   existing alert stops firing.
 *
 * ALSO — the duplicate-looking email
 *   The two rows were RappelConso fiches 23501 and 23502: the same lot
 *   (VA238F001) of foie gras from the same producer, published the same day,
 *   one sold at the factory shop and one through METRO. Two notices of ONE
 *   incident, and the register says so — both carry
 *   [incident:fr:truffe-perigourdine-2026-09-11] in Notes, one of the 14
 *   public columns. The weekly report already counts them once; this email
 *   did not know to look. sendAlertMatchEmail_ now counts incidents first,
 *   then notices, and tags the rows that share one. Both rows are still
 *   listed: each names a different product and use-by date.
 *
 * NEW ADMIN FUNCTIONS
 *   test_fsisAlertVocab()  — 30+ matcher cases plus a vocabulary integrity
 *                            check. Sends nothing, writes nothing.
 *   auditStoredRules()     — lists active rules whose stored term is no
 *                            longer understood, with the reason. Run once
 *                            after deploying.'''


def _find_function(src, name):
    """Return (start, end) char offsets of `function name(...) { ... }`."""
    m = re.search(r"^function\s+%s\s*\(" % re.escape(name), src, re.M)
    if not m:
        raise SystemExit("base file: function %s not found" % name)
    i = src.index("{", m.end() - 1)
    depth, j = 0, i
    in_s = in_d = in_t = in_line = in_block = in_rx = False
    prev = ""
    while j < len(src):
        c = src[j]
        nxt = src[j + 1] if j + 1 < len(src) else ""
        if in_line:
            if c == "\n":
                in_line = False
        elif in_block:
            if c == "*" and nxt == "/":
                in_block = False
                j += 1
        elif in_s:
            if c == "\\":
                j += 1
            elif c == "'":
                in_s = False
        elif in_d:
            if c == "\\":
                j += 1
            elif c == '"':
                in_d = False
        elif in_t:
            if c == "\\":
                j += 1
            elif c == "`":
                in_t = False
        elif in_rx:
            if c == "\\":
                j += 1
            elif c == "/":
                in_rx = False
        else:
            if c == "/" and nxt == "/":
                in_line = True
                j += 1
            elif c == "/" and nxt == "*":
                in_block = True
                j += 1
            elif c == "/" and prev in "(,=:[!&|?{;+" :
                in_rx = True
            elif c == "'":
                in_s = True
            elif c == '"':
                in_d = True
            elif c == "`":
                in_t = True
            elif c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    return m.start(), j + 1
        if not c.isspace():
            prev = c
        j += 1
    raise SystemExit("base file: unbalanced braces in %s" % name)


def _leading_doc(src, start):
    """Extend `start` backwards over an immediately preceding /** ... */ block."""
    head = src[:start].rstrip()
    if head.endswith("*/"):
        k = head.rfind("/**")
        if k >= 0 and "\n" not in src[head.rfind("*/") + 2:start].strip():
            return k
    return start


GS_VOCAB_BANNER = """

// =============================================================================
// ALERT VOCABULARY  (generated — see the 2026-09-14 revision note above)
// =============================================================================
"""


def render_gs() -> str:
    src = open(BASE_PATH, encoding="utf-8").read()

    # 1. revision note, spliced in just before the header docstring closes.
    anchor = "\n * ---------------------------------------------------------------------------\n * PIPELINE (unchanged)"
    if anchor not in src:
        raise SystemExit("base file: header PIPELINE anchor not found")
    src = src.replace(anchor, "\n" + REVISION_NOTE + anchor, 1)

    # 2. vocabulary gate in processAlertSubmission_.
    gate_anchor = ("  if (!email || !name)          return {ok: false, error: 'missing_identity'};\n"
                   "  if (!slot1_val && !slot2_val) return {ok: false, error: 'no_criteria'};\n")
    if gate_anchor not in src:
        raise SystemExit("base file: submission sanity-check anchor not found")
    src = src.replace(gate_anchor, gate_anchor + VOCAB_GATE, 1)

    # 3. + 4. swap the two functions.
    for name, replacement in (("recallMatchesCriterion_", GS_ENGINE),
                              ("sendAlertMatchEmail_", GS_MAILER)):
        a, b = _find_function(src, name)
        a = _leading_doc(src, a)
        src = src[:a] + replacement.strip("\n") + src[b:]

    # 5. vocabulary tables, immediately before the MATCHER banner.
    vocab = [GS_VOCAB_BANNER.strip("\n"), "", BEGIN, ""]
    vocab.append("var FSIS_VOCAB_VERSION = %s;" % js(VERSION))
    vocab.append("")
    vocab.append(_js_map("PATHOGEN_VOCAB", V.PATHOGEN))
    vocab.append("")
    vocab.append(_js_map("PRODUCT_VOCAB", V.PRODUCT))
    vocab.append("")
    vocab.append(_js_array("COUNTRY_LIST", V.COUNTRY))
    vocab.append("")
    vocab.append(_js_map("COUNTRY_ALIASES", V.COUNTRY_ALIASES))
    vocab.append("")
    vocab.append(_js_map("PATHOGEN_LEGACY", V.PATHOGEN_LEGACY))
    vocab.append("")
    vocab.append(_js_map("RETIRED_PATHOGEN", V.RETIRED_PATHOGEN))
    vocab.append("")
    vocab.append(_js_map("RETIRED_PRODUCT", V.RETIRED_PRODUCT))
    vocab.append("")
    vocab.append(END)
    matcher_banner = ("// =============================================================================\n"
                      "// MATCHER\n"
                      "// =============================================================================")
    if matcher_banner not in src:
        raise SystemExit("base file: MATCHER banner not found")
    src = src.replace(matcher_banner, "\n".join(vocab) + "\n\n\n" + matcher_banner, 1)

    # 6. new admin + self-test functions, appended.
    src = src.rstrip("\n") + "\n" + GS_ADMIN + GS_TESTS.rstrip("\n") + "\n"
    return src


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("pass --write or --check")

    targets = [(GS_PATH, render_gs()), (HTML_PATH, render_html())]
    stale = []
    for path, want in targets:
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == want:
            continue
        stale.append(path)
        if args.write:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(want)

    rel = [os.path.relpath(p, ROOT) for p in stale]
    if args.write:
        print("wrote: " + (", ".join(rel) if rel else "(nothing — already current)"))
        return 0
    if stale:
        print("STALE: " + ", ".join(rel))
        print("run: python3 tools/gen_alert_vocab.py --write")
        return 1
    print("alert vocabulary is in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
